In [2]:
import numpy as np

In [13]:
a = (1+np.arange(5))**2

In [14]:
a

array([ 1,  4,  9, 16, 25])

In [15]:
b = np.zeros(a.size + 3*(a.size - 1))

In [16]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
b[::(3 + 1)] = a

In [18]:
b

array([ 1.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  9.,  0.,  0.,  0., 16.,
        0.,  0.,  0., 25.])

In [24]:
for start in range(3):
    b[(1 + start)::(1 + 3)] = a[:-1] + (a[1:] - a[:-1])*(1 + start)/(3 + 1)

In [25]:
b

array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ,  5.25,  6.5 ,  7.75,  9.  ,
       10.75, 12.5 , 14.25, 16.  , 18.25, 20.5 , 22.75, 25.  ])

In [19]:
np.linspace(1, 4, 5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [26]:
def subsample_array(a, n=1):
    new = np.empty(a.size + n*(a.size - 1))
    new[::(n + 1)] = a
    for start in range(n):
        new[(1 + start)::(n + 1)] = a[:-1] + (a[1:] - a[:-1])*(1 + start)/(1 + n)
    return new

In [28]:
t = (2 + np.arange(4))**3
print(t)
print(subsample_array(t))
print(subsample_array(t, 2))
print(subsample_array(t, 4))

[  8  27  64 125]
[  8.   17.5  27.   45.5  64.   94.5 125. ]
[  8.          14.33333333  20.66666667  27.          39.33333333
  51.66666667  64.          84.33333333 104.66666667 125.        ]
[  8.   11.8  15.6  19.4  23.2  27.   34.4  41.8  49.2  56.6  64.   76.2
  88.4 100.6 112.8 125. ]
